---
deployment:
  tasks:
    - export APPPATH=/home/wwhafiz/hafizuna_core
    - export PUBLICPATH=/home/wwhafiz/public_html

    - /bin/mkdir -p $APPPATH
    - /bin/rm -rf $APPPATH/*
    - /bin/rm -rf $PUBLICPATH/*

    - /bin/cp -R app bootstrap config database resources routes storage artisan composer.json composer.lock $APPPATH
    - /bin/cp -R public/. $PUBLICPATH
